## buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      # Set COMMIT_INFO variables to send Git specifics to Cypress Dashboard when recording
      # https://docs.cypress.io/guides/continuous-integration/introduction#Git-information
      - npm ci
  pre_build:
    commands:

      - echo "we are in the pre build phase"
      - npm run cy:verify
      - npm run cy:info
  build:
    commands:
      - echo "this is build section inside buildspec.yml file"
      - npm run test